# Generated by Django 6.1.1 on 2026-09-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score1',
            old_name='name',
            new_name='myname1',
        ),
        migrations.RenameField(
            model_name='score1',
            old_name='score',
            new_name='score1',
        ),
    ]
